- name: Configure Web Server
  hosts: web-server
  become: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

  tasks:
    - name: "Update Packages"
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    
    - name: "Upgrade Packages"
      ansible.builtin.apt:
        name: "*"
        state: latest
    
    - name: "Install required system packages"
      ansible.builtin.apt:
        name: "{{packages}}"
        state: present
    
    - name: "Add Docker GPG key"
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: "Add Docker repository"
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: "Update apt and install docker-ce"  
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
    
    - name: "Install Docker module for python"
      ansible.builtin.pip:
        name: docker
    
    - name: "Create Page`s directory"
      ansible.builtin.file:
        state: directory
        path: ~/pages/firts_page
        owner: www-data
        group: www-data
        mode: 0755
    
    - name: "Pull nginx image"
      community.docker.docker_image:
        name: nginx:stable-alpine3.20
        
        source: pull
    
    - name: "Start nginx contanier"
      community.docker.docker_container:
        name: nginx_con
        image: nginx:stable-alpine3.20
        state: started
        volumes:
          - ~/pages/firts_page:/usr/share/nginx/html/
        ports:
          - 80:80
        restart: true
        restart_policy: "always"

    - name: "Copy Html Page To The Server"
      ansible.builtin.copy:
        src: /home/ubuntu/bash-practise/megalapot/ansible_files/page/index.html
        dest: ~/pages/firts_page/index.html
        mode: 0755
        owner: www-data
        group: www-data
